version: '3.9'

services:
  api1:
    image: isadoramsouza/api-rinha-backend:latest
    hostname: api1
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/rinhabackenddb
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=rinha
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.0GB'

  api2:
    image: isadoramsouza/api-rinha-backend:latest
    hostname: api2
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db:5432/rinhabackenddb
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=rinha
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.0GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.1GB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinhabackenddb
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'

networks:
  default:
    driver: bridge
    name: rinha